//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConocenosResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConocenosResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.ConocenosResourceUS", typeof(ConocenosResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Know us.
        /// </summary>
        internal static string conocenos {
            get {
                return ResourceManager.GetString("conocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nuestrosServiciosIngles.
        /// </summary>
        internal static string nuestroServicio {
            get {
                return ResourceManager.GetString("nuestroServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our services.
        /// </summary>
        internal static string nuestrosServicios {
            get {
                return ResourceManager.GetString("nuestrosServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our Values.
        /// </summary>
        internal static string nuestrosValores {
            get {
                return ResourceManager.GetString("nuestrosValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a quienEsIngles.
        /// </summary>
        internal static string quienEs {
            get {
                return ResourceManager.GetString("quienEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a servicioBoletosIngles.
        /// </summary>
        internal static string servicioBoletos {
            get {
                return ResourceManager.GetString("servicioBoletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a servicioHotelIngles.
        /// </summary>
        internal static string servicioHotel {
            get {
                return ResourceManager.GetString("servicioHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a servicioPaquetesIngles.
        /// </summary>
        internal static string servicioPaquetes {
            get {
                return ResourceManager.GetString("servicioPaquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a servicioTrasladoIngles.
        /// </summary>
        internal static string servicioTraslado {
            get {
                return ResourceManager.GetString("servicioTraslado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Travel for Chiapas.
        /// </summary>
        internal static string viajesItzaa {
            get {
                return ResourceManager.GetString("viajesItzaa", resourceCulture);
            }
        }
    }
}
