//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactoResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactoResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.ContactoResourceUS", typeof(ContactoResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        internal static string asunto {
            get {
                return ResourceManager.GetString("asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        internal static string contactano {
            get {
                return ResourceManager.GetString("contactano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contactanosIngles.
        /// </summary>
        internal static string contactanos {
            get {
                return ResourceManager.GetString("contactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send message.
        /// </summary>
        internal static string enviarMensaje {
            get {
                return ResourceManager.GetString("enviarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for contacting us.
        /// </summary>
        internal static string gracias {
            get {
                return ResourceManager.GetString("gracias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours we can contact you.
        /// </summary>
        internal static string horarioContacto {
            get {
                return ResourceManager.GetString("horarioContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete the form below.
        /// </summary>
        internal static string lleneFormulario {
            get {
                return ResourceManager.GetString("lleneFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        internal static string mensaje {
            get {
                return ResourceManager.GetString("mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
    }
}
