//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CotizarToursResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CotizarToursResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.CotizarToursResourceUS", typeof(CotizarToursResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrival airport.
        /// </summary>
        internal static string aeropuertoLlegada {
            get {
                return ResourceManager.GetString("aeropuertoLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure airport.
        /// </summary>
        internal static string aeropuertoSalida {
            get {
                return ResourceManager.GetString("aeropuertoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mother&apos;s last name.
        /// </summary>
        internal static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        internal static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail not valid.
        /// </summary>
        internal static string correoNoValido {
            get {
                return ResourceManager.GetString("correoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QUOTE.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quote Tour.
        /// </summary>
        internal static string cotizarTours {
            get {
                return ResourceManager.GetString("cotizarTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It features airline ticket.
        /// </summary>
        internal static string cuentaBoletoAvion {
            get {
                return ResourceManager.GetString("cuentaBoletoAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrival date.
        /// </summary>
        internal static string fechaLlegada {
            get {
                return ResourceManager.GetString("fechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure date.
        /// </summary>
        internal static string fechaSalida {
            get {
                return ResourceManager.GetString("fechaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for subscribing.
        /// </summary>
        internal static string graciaSuscribirse {
            get {
                return ResourceManager.GetString("graciaSuscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In.
        /// </summary>
        internal static string horaLlegada {
            get {
                return ResourceManager.GetString("horaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure time.
        /// </summary>
        internal static string horaSalida {
            get {
                return ResourceManager.GetString("horaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor 0-2.
        /// </summary>
        internal static string menores14 {
            get {
                return ResourceManager.GetString("menores14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor 3-10.
        /// </summary>
        internal static string menores511 {
            get {
                return ResourceManager.GetString("menores511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEED HELP ?.
        /// </summary>
        internal static string necesitaAyuda {
            get {
                return ResourceManager.GetString("necesitaAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you need help feel free to contact us and we will support it..
        /// </summary>
        internal static string necesitaAyudaComunicarse {
            get {
                return ResourceManager.GetString("necesitaAyudaComunicarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We could not make the price would appreciate it if you could communicate to office phones.
        /// </summary>
        internal static string noPudoRealizarCotizacion {
            get {
                return ResourceManager.GetString("noPudoRealizarCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Adults.
        /// </summary>
        internal static string numeroAdultos {
            get {
                return ResourceManager.GetString("numeroAdultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total number of people do not match the breakdown by rank.
        /// </summary>
        internal static string numeroPersonaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total number of people do not match the breakdown by rank.
        /// </summary>
        internal static string numeroPersonaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of people.
        /// </summary>
        internal static string numeroPersonas {
            get {
                return ResourceManager.GetString("numeroPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of right people.
        /// </summary>
        internal static string numeroPersonasCorrectas {
            get {
                return ResourceManager.GetString("numeroPersonasCorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In a maximum term of 48, one of our agents will contact you by email to answer your request..
        /// </summary>
        internal static string termino24Horas {
            get {
                return ResourceManager.GetString("termino24Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tour.
        /// </summary>
        internal static string tours {
            get {
                return ResourceManager.GetString("tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please specify the range of people traveling.
        /// </summary>
        internal static string validacionLoad1 {
            get {
                return ResourceManager.GetString("validacionLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please indicate the number of people per room , remember that only a maximum of 4 persons per room is allowed.
        /// </summary>
        internal static string validacionLoad2 {
            get {
                return ResourceManager.GetString("validacionLoad2", resourceCulture);
            }
        }
    }
}
