//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CotizarPaqueteResourceMX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CotizarPaqueteResourceMX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.CotizarPaqueteResourceMX", typeof(CotizarPaqueteResourceMX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aeropuerto de Llegada.
        /// </summary>
        internal static string aeropuertoLlegada {
            get {
                return ResourceManager.GetString("aeropuertoLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aeropuerto de Salida.
        /// </summary>
        internal static string aeropuertoSalida {
            get {
                return ResourceManager.GetString("aeropuertoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Armar paquete VIP.
        /// </summary>
        internal static string armarPaqueteVip {
            get {
                return ResourceManager.GetString("armarPaqueteVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría de Hotel.
        /// </summary>
        internal static string categoriaHotel {
            get {
                return ResourceManager.GetString("categoriaHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo no válido.
        /// </summary>
        internal static string CorreoNoValido {
            get {
                return ResourceManager.GetString("CorreoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotización Paquete.
        /// </summary>
        internal static string cotizacionPaquete {
            get {
                return ResourceManager.GetString("cotizacionPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COTIZAR.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizar Paquete.
        /// </summary>
        internal static string cotizarpaquetes {
            get {
                return ResourceManager.GetString("cotizarpaquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta con boleto de avión.
        /// </summary>
        internal static string cuentaBoletoAvion {
            get {
                return ResourceManager.GetString("cuentaBoletoAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Llegada.
        /// </summary>
        internal static string fechaLlegada {
            get {
                return ResourceManager.GetString("fechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Salida.
        /// </summary>
        internal static string fechaSalida {
            get {
                return ResourceManager.GetString("fechaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por suscribirse.
        /// </summary>
        internal static string graciasSuscribirse {
            get {
                return ResourceManager.GetString("graciasSuscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Llegada.
        /// </summary>
        internal static string horaLlegada {
            get {
                return ResourceManager.GetString("horaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Salida.
        /// </summary>
        internal static string horaSalida {
            get {
                return ResourceManager.GetString("horaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menores de 0-2.
        /// </summary>
        internal static string menores14 {
            get {
                return ResourceManager.GetString("menores14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menores de 3-10.
        /// </summary>
        internal static string menores511 {
            get {
                return ResourceManager.GetString("menores511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por políticas internas de los hoteles, solo se permiten 4 personas máximo por habitación. En caso de requerir una cantidad mayor de personas por habitación, escríbanos para que un asesor le ayude..
        /// </summary>
        internal static string msghabitaciones {
            get {
                return ResourceManager.GetString("msghabitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NECESITA AYUDA.
        /// </summary>
        internal static string necesitaAyuda {
            get {
                return ResourceManager.GetString("necesitaAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si necesita ayuda no dude en comunicarse con nosotros y con gusto lo apoyaremos..
        /// </summary>
        internal static string necesitaAyudaComunicarse {
            get {
                return ResourceManager.GetString("necesitaAyudaComunicarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo realizar la cotización le agradeceríamos si se pudiera comunicar a los teléfonos de la oficina.
        /// </summary>
        internal static string noSePudoRealizarCotizacion {
            get {
                return ResourceManager.GetString("noSePudoRealizarCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Adultos.
        /// </summary>
        internal static string numeroAdultos {
            get {
                return ResourceManager.GetString("numeroAdultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de camas asignadas mayor a la solicitada.
        /// </summary>
        internal static string numeroCamaAsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamaAsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de camas asignadas menor a la solicitada.
        /// </summary>
        internal static string numeroCamaAsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamaAsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de camas.
        /// </summary>
        internal static string numeroCamas {
            get {
                return ResourceManager.GetString("numeroCamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de camas asignadas menor a la solicitada.
        /// </summary>
        internal static string numeroCamasAsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamasAsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de habitaciones.
        /// </summary>
        internal static string numeroHabitaciones {
            get {
                return ResourceManager.GetString("numeroHabitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 0-2 asignadas mayor a la solicitada.
        /// </summary>
        internal static string numeroNiño14AsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño14AsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 0-2 asiganados menor a la solicitada.
        /// </summary>
        internal static string numeroNiño14AsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño14AsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 3-10 asignadas mayor a la solicitada.
        /// </summary>
        internal static string numeroNiño51AsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño51AsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 3-10 asignados menor a la solicitada.
        /// </summary>
        internal static string numeroNiño51AsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño51AsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 0-2.
        /// </summary>
        internal static string numeroNiños14 {
            get {
                return ResourceManager.GetString("numeroNiños14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 3-10.
        /// </summary>
        internal static string numeroNiños511 {
            get {
                return ResourceManager.GetString("numeroNiños511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas Adultas asiganadas mayor a la solicitada.
        /// </summary>
        internal static string numeroPersonaAdultaAsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaAdultaAsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas Adultas asiganadas menor a la solicitada.
        /// </summary>
        internal static string numeroPersonaAdultaAsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaAdultaAsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de personas por habitación es correcta.
        /// </summary>
        internal static string numeroPersonaAsignadaCorrectamente {
            get {
                return ResourceManager.GetString("numeroPersonaAsignadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información de personas por edad es correcta.
        /// </summary>
        internal static string numeroPersonaCorrecta {
            get {
                return ResourceManager.GetString("numeroPersonaCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad total de personas no coinciden con el desglose por rango.
        /// </summary>
        internal static string numeroPersonaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad total de personas no coinciden con el desglose por rango.
        /// </summary>
        internal static string numeroPersonaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de personas.
        /// </summary>
        internal static string numeroPersonas {
            get {
                return ResourceManager.GetString("numeroPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas Adultas asiganadas mayor a la solicitada.
        /// </summary>
        internal static string numeroPersonasAdultasAsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasAdultasAsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas Adultas asiganadas menor a la solicitada.
        /// </summary>
        internal static string numeroPersonasAdultasAsignadaMenosSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasAdultasAsignadaMenosSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información de personas por edad es correcta.
        /// </summary>
        internal static string numeroPersonasCorrectas {
            get {
                return ResourceManager.GetString("numeroPersonasCorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas por habitación.
        /// </summary>
        internal static string numeroPersonasHabitacion {
            get {
                return ResourceManager.GetString("numeroPersonasHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad total de personas no coinciden con el desglose por rango.
        /// </summary>
        internal static string numeroPersonasMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad total de personas no coinciden con el desglose por rango.
        /// </summary>
        internal static string numeroPersonasMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LE OFRECEMOS EL SERVICIO DE PAQUETES VIP, DONDE USTED DECIDE DÓNDE VISITAR Y TODAS LAS CARACTERÍSTICAS DE SU VIAJE PARA QUE SU EXPERIENCIA SEA ÚNICA E INOLVIDABLE.
        /// </summary>
        internal static string ofrecemosServicioPaqueteVip {
            get {
                return ResourceManager.GetString("ofrecemosServicioPaqueteVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por contactarnos.
        /// </summary>
        internal static string termino24Horas {
            get {
                return ResourceManager.GetString("termino24Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡GRACIAS!, la información sobre su solicitud ya fue enviada a su correo. Agradecemos verificar su carpeta de spam o correos no deseados..
        /// </summary>
        internal static string termino24Horas2 {
            get {
                return ResourceManager.GetString("termino24Horas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En un término máximo de 48, uno de nuestros agentes se contactará con usted por medio de correo electrónico para atender su solicitud..
        /// </summary>
        internal static string termino24Horas3 {
            get {
                return ResourceManager.GetString("termino24Horas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor especifique el rango de las personas que viajaran.
        /// </summary>
        internal static string validacionLoad1 {
            get {
                return ResourceManager.GetString("validacionLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, indique la cantidad de personas por habitación. Recuerde que solo se permite un máximo de 4 personas por habitación..
        /// </summary>
        internal static string validacionLoad2 {
            get {
                return ResourceManager.GetString("validacionLoad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una o más habitaciones superan el máximo de personas permitidas.
        /// </summary>
        internal static string validacionWill01 {
            get {
                return ResourceManager.GetString("validacionWill01", resourceCulture);
            }
        }
    }
}
