//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CotizarHotelResourceMX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CotizarHotelResourceMX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.CotizarHotelResourceMX", typeof(CotizarHotelResourceMX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aeropuerto de llegada.
        /// </summary>
        internal static string aeropuertoLlegada {
            get {
                return ResourceManager.GetString("aeropuertoLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aeropuerto de Salida.
        /// </summary>
        internal static string aeropuertoSalida {
            get {
                return ResourceManager.GetString("aeropuertoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria de Hotel.
        /// </summary>
        internal static string categoriaHotel {
            get {
                return ResourceManager.GetString("categoriaHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo no valido.
        /// </summary>
        internal static string correoNoValido {
            get {
                return ResourceManager.GetString("correoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotización Hotel.
        /// </summary>
        internal static string cotizacionHotel {
            get {
                return ResourceManager.GetString("cotizacionHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COTIZAR.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizar Hotel.
        /// </summary>
        internal static string cotizarhotel {
            get {
                return ResourceManager.GetString("cotizarhotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta con boleto de avión.
        /// </summary>
        internal static string cuentaBoletoAvion {
            get {
                return ResourceManager.GetString("cuentaBoletoAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Llegada.
        /// </summary>
        internal static string fechaLlegada {
            get {
                return ResourceManager.GetString("fechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Salida.
        /// </summary>
        internal static string fechaSalida {
            get {
                return ResourceManager.GetString("fechaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por suscribirse.
        /// </summary>
        internal static string graciaSuscribirse {
            get {
                return ResourceManager.GetString("graciaSuscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Llegada.
        /// </summary>
        internal static string horaLlegada {
            get {
                return ResourceManager.GetString("horaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Salida.
        /// </summary>
        internal static string horaSalida {
            get {
                return ResourceManager.GetString("horaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menores de 1-4.
        /// </summary>
        internal static string menores14 {
            get {
                return ResourceManager.GetString("menores14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menores de 5-11.
        /// </summary>
        internal static string menores511 {
            get {
                return ResourceManager.GetString("menores511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NECESITA AYUDA ?.
        /// </summary>
        internal static string necesitaAyuda {
            get {
                return ResourceManager.GetString("necesitaAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si necesita ayuda no dude en comunicarse con nosotros y con gusto lo apoyaremos..
        /// </summary>
        internal static string necesitaAyudaComunicarse {
            get {
                return ResourceManager.GetString("necesitaAyudaComunicarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo realizar la cotización le agradeceriamos si se pudiera comunicar a los telefonos de la oficina.
        /// </summary>
        internal static string noPudoRealizarCotizacion {
            get {
                return ResourceManager.GetString("noPudoRealizarCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Adultos.
        /// </summary>
        internal static string numeroAdultos {
            get {
                return ResourceManager.GetString("numeroAdultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Camas asignadas mayor a la solicitada.
        /// </summary>
        internal static string numeroCamaAsigMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamaAsigMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Camas asignadas menor a la solicitada.
        /// </summary>
        internal static string numeroCamaAsigMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamaAsigMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Camas.
        /// </summary>
        internal static string numeroCamas {
            get {
                return ResourceManager.GetString("numeroCamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Habitaciones.
        /// </summary>
        internal static string numeroHabitaciones {
            get {
                return ResourceManager.GetString("numeroHabitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 1-4.
        /// </summary>
        internal static string numeroNiño14 {
            get {
                return ResourceManager.GetString("numeroNiño14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 1-4 asiganadas mayor a la solicitada.
        /// </summary>
        internal static string numeroNiño14AsigMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño14AsigMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 1-4 asiganados menor a la solicitada.
        /// </summary>
        internal static string numeroNiño14AsigMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño14AsigMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 5-11.
        /// </summary>
        internal static string numeroNiño511 {
            get {
                return ResourceManager.GetString("numeroNiño511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 5-1 asiganadas mayor a la solicitada.
        /// </summary>
        internal static string numeroNiño51AsigMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño51AsigMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Niños 5-1 asiganados menor a la solicitada.
        /// </summary>
        internal static string numeroNiño51AsigMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño51AsigMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas Adultas asiganadas mayor a la solicitada.
        /// </summary>
        internal static string numeroPersonaAdultaAsigMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaAdultaAsigMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas Adultas asiganadas menor a la solicitada.
        /// </summary>
        internal static string numeroPersonaAdultaAsigMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaAdultaAsigMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de personas por habitación es correcta.
        /// </summary>
        internal static string numeroPersonaAsigCorrectamente {
            get {
                return ResourceManager.GetString("numeroPersonaAsigCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas.
        /// </summary>
        internal static string numeroPersonas {
            get {
                return ResourceManager.GetString("numeroPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información de personas por edad es correcta.
        /// </summary>
        internal static string numeroPersonasCorrectas {
            get {
                return ResourceManager.GetString("numeroPersonasCorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de personas por habitación.
        /// </summary>
        internal static string numeroPersonasHabitacion {
            get {
                return ResourceManager.GetString("numeroPersonasHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad total de personas no coinciden con el desglose por rango.
        /// </summary>
        internal static string numeroPersonasMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad total de personas no coinciden con el desglose por rango.
        /// </summary>
        internal static string numeroPersonasMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LE OFRECEMOS EL SERVICIO DE PAQUETES VIP, DONDE USTED USTED DECIDE QUE VISITAR Y TODAS LAS CARACTERÍSTICAS DE SU VIAJE PARA QUE SU EXPERIENCIA SEA ÚNICA E INOLVIDABLE.
        /// </summary>
        internal static string ofrecemosServicioPaquetesVip {
            get {
                return ResourceManager.GetString("ofrecemosServicioPaquetesVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En un termino de 24 horas uno de nuestros agentes les notificara mediante correo si hay disponibilidad de los servicios indicados.
        /// </summary>
        internal static string termino24Horas {
            get {
                return ResourceManager.GetString("termino24Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor especifique el rango de las personas que viajaran.
        /// </summary>
        internal static string validacionLoad1 {
            get {
                return ResourceManager.GetString("validacionLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, indique la cantidad de personas por habitación, Recuerde que solo se permite un maximo de 4 personas por habitación..
        /// </summary>
        internal static string validacionLoad2 {
            get {
                return ResourceManager.GetString("validacionLoad2", resourceCulture);
            }
        }
    }
}
