//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CotizarPaqueteResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CotizarPaqueteResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.CotizarPaqueteResourceUS", typeof(CotizarPaqueteResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrival airport.
        /// </summary>
        internal static string aeropuertoLlegada {
            get {
                return ResourceManager.GetString("aeropuertoLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure airport.
        /// </summary>
        internal static string aeropuertoSalida {
            get {
                return ResourceManager.GetString("aeropuertoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mother&apos;s last name.
        /// </summary>
        internal static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        internal static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create VIP package.
        /// </summary>
        internal static string armarPaqueteVip {
            get {
                return ResourceManager.GetString("armarPaqueteVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotel Category.
        /// </summary>
        internal static string categoriaHotel {
            get {
                return ResourceManager.GetString("categoriaHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail not valid.
        /// </summary>
        internal static string CorreoNoValido {
            get {
                return ResourceManager.GetString("CorreoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quote Package.
        /// </summary>
        internal static string cotizacionPaquete {
            get {
                return ResourceManager.GetString("cotizacionPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QUOTE.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quoting Package.
        /// </summary>
        internal static string cotizarpaquetes {
            get {
                return ResourceManager.GetString("cotizarpaquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It features airline ticket.
        /// </summary>
        internal static string cuentaBoletoAvion {
            get {
                return ResourceManager.GetString("cuentaBoletoAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrival date.
        /// </summary>
        internal static string fechaLlegada {
            get {
                return ResourceManager.GetString("fechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure date.
        /// </summary>
        internal static string fechaSalida {
            get {
                return ResourceManager.GetString("fechaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for subscribing.
        /// </summary>
        internal static string graciasSuscribirse {
            get {
                return ResourceManager.GetString("graciasSuscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In.
        /// </summary>
        internal static string horaLlegada {
            get {
                return ResourceManager.GetString("horaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure time.
        /// </summary>
        internal static string horaSalida {
            get {
                return ResourceManager.GetString("horaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor 0-2.
        /// </summary>
        internal static string menores14 {
            get {
                return ResourceManager.GetString("menores14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor 3-10.
        /// </summary>
        internal static string menores511 {
            get {
                return ResourceManager.GetString("menores511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By internal policies of the Hotels, only 4 people maximum per room are allowed. If you require more people per room, write to us for an advisor to help you..
        /// </summary>
        internal static string msghabitaciones {
            get {
                return ResourceManager.GetString("msghabitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEED HELP.
        /// </summary>
        internal static string necesitaAyuda {
            get {
                return ResourceManager.GetString("necesitaAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you need help feel free to contact us and we will support it..
        /// </summary>
        internal static string necesitaAyudaComunicarse {
            get {
                return ResourceManager.GetString("necesitaAyudaComunicarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We could not make the price would appreciate it if you could communicate to office phones.
        /// </summary>
        internal static string noSePudoRealizarCotizacion {
            get {
                return ResourceManager.GetString("noSePudoRealizarCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Adults.
        /// </summary>
        internal static string numeroAdultos {
            get {
                return ResourceManager.GetString("numeroAdultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of beds allocated more than requested.
        /// </summary>
        internal static string numeroCamaAsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamaAsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of beds allocated less than requested.
        /// </summary>
        internal static string numeroCamaAsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamaAsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of beds.
        /// </summary>
        internal static string numeroCamas {
            get {
                return ResourceManager.GetString("numeroCamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of beds allocated less than requested.
        /// </summary>
        internal static string numeroCamasAsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroCamasAsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of rooms.
        /// </summary>
        internal static string numeroHabitaciones {
            get {
                return ResourceManager.GetString("numeroHabitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boys 0-2 Number assigned more than requested.
        /// </summary>
        internal static string numeroNiño14AsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño14AsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boys 0-2 Number assigned less than requested.
        /// </summary>
        internal static string numeroNiño14AsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño14AsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of children 3-10 assigned more than requested.
        /// </summary>
        internal static string numeroNiño51AsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño51AsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of children 3-10 allocated less than requested.
        /// </summary>
        internal static string numeroNiño51AsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroNiño51AsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Boys 0-2.
        /// </summary>
        internal static string numeroNiños14 {
            get {
                return ResourceManager.GetString("numeroNiños14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Children 3-10.
        /// </summary>
        internal static string numeroNiños511 {
            get {
                return ResourceManager.GetString("numeroNiños511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of adults assigned more than requested.
        /// </summary>
        internal static string numeroPersonaAdultaAsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaAdultaAsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of adults assigned less than requested.
        /// </summary>
        internal static string numeroPersonaAdultaAsignadaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaAdultaAsignadaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of people per room is correct.
        /// </summary>
        internal static string numeroPersonaAsignadaCorrectamente {
            get {
                return ResourceManager.GetString("numeroPersonaAsignadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information age people is correct.
        /// </summary>
        internal static string numeroPersonaCorrecta {
            get {
                return ResourceManager.GetString("numeroPersonaCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total number of people do not match the breakdown by rank.
        /// </summary>
        internal static string numeroPersonaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total number of people do not match the breakdown by rank.
        /// </summary>
        internal static string numeroPersonaMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonaMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total persons.
        /// </summary>
        internal static string numeroPersonas {
            get {
                return ResourceManager.GetString("numeroPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of adults assigned more than requested.
        /// </summary>
        internal static string numeroPersonasAdultasAsignadaMayorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasAdultasAsignadaMayorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of adults assigned less than requested.
        /// </summary>
        internal static string numeroPersonasAdultasAsignadaMenosSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasAdultasAsignadaMenosSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information age people is correct.
        /// </summary>
        internal static string numeroPersonasCorrectas {
            get {
                return ResourceManager.GetString("numeroPersonasCorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of persons per room.
        /// </summary>
        internal static string numeroPersonasHabitacion {
            get {
                return ResourceManager.GetString("numeroPersonasHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total number of people do not match the breakdown by rank.
        /// </summary>
        internal static string numeroPersonasMenorSolicitada {
            get {
                return ResourceManager.GetString("numeroPersonasMenorSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WE OFFER SERVICE VIP PACKAGES WHERE YOU DECIDE TO VISIT YOU AND ALL THE FEATURES OF YOUR TRIP TO EXPERIENCE UNIQUE AND UNFORGETTABLE.
        /// </summary>
        internal static string ofrecemosServicioPaqueteVip {
            get {
                return ResourceManager.GetString("ofrecemosServicioPaqueteVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for contacting us.
        /// </summary>
        internal static string termino24Horas {
            get {
                return ResourceManager.GetString("termino24Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THANK YOU !, the information about your request has already been sent to your email. We appreciate checking your spam folder or junk mail..
        /// </summary>
        internal static string termino24Horas2 {
            get {
                return ResourceManager.GetString("termino24Horas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In a maximum term of 48, one of our agents will contact you by email to answer your request..
        /// </summary>
        internal static string termino24Horas3 {
            get {
                return ResourceManager.GetString("termino24Horas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please specify the range of people traveling.
        /// </summary>
        internal static string validacionLoad1 {
            get {
                return ResourceManager.GetString("validacionLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please indicate the number of people per room , remember that only a maximum of 4 persons per room is allowed.
        /// </summary>
        internal static string validacionLoad2 {
            get {
                return ResourceManager.GetString("validacionLoad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more rooms exceed the maximum number of people allowed.
        /// </summary>
        internal static string validacionWill01 {
            get {
                return ResourceManager.GetString("validacionWill01", resourceCulture);
            }
        }
    }
}
