//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetallePaqueteResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetallePaqueteResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.DetallePaqueteResourceUS", typeof(DetallePaqueteResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create VIP package.
        /// </summary>
        internal static string armarPaquete {
            get {
                return ResourceManager.GetString("armarPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WE OFFER SERVICE VIP PACKAGES WHERE YOU DECIDE TO VISIT YOU AND ALL THE FEATURES OF YOUR TRIP TO EXPERIENCE UNIQUE AND UNFORGETTABLE.
        /// </summary>
        internal static string armarPaqueteVIP {
            get {
                return ResourceManager.GetString("armarPaqueteVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quote.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcionIngles.
        /// </summary>
        internal static string descripcionIGet {
            get {
                return ResourceManager.GetString("descripcionIGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcionIngles.
        /// </summary>
        internal static string descripcionPGet {
            get {
                return ResourceManager.GetString("descripcionPGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Since.
        /// </summary>
        internal static string desde {
            get {
                return ResourceManager.GetString("desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail Package.
        /// </summary>
        internal static string detallePaquete {
            get {
                return ResourceManager.GetString("detallePaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        internal static string detalles {
            get {
                return ResourceManager.GetString("detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details Tour.
        /// </summary>
        internal static string detalleTour {
            get {
                return ResourceManager.GetString("detalleTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days.
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End of service.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a findeservicios_ingles.
        /// </summary>
        internal static string finservicio {
            get {
                return ResourceManager.GetString("finservicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Includes.
        /// </summary>
        internal static string incluye {
            get {
                return ResourceManager.GetString("incluye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a incluye_ingles.
        /// </summary>
        internal static string incluyeGet {
            get {
                return ResourceManager.GetString("incluyeGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Itinerary.
        /// </summary>
        internal static string itinerario {
            get {
                return ResourceManager.GetString("itinerario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map.
        /// </summary>
        internal static string mapa {
            get {
                return ResourceManager.GetString("mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need Assistance.
        /// </summary>
        internal static string necesitaAsistencia {
            get {
                return ResourceManager.GetString("necesitaAsistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nights.
        /// </summary>
        internal static string noches {
            get {
                return ResourceManager.GetString("noches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a not Included.
        /// </summary>
        internal static string noIncluye {
            get {
                return ResourceManager.GetString("noIncluye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a noincluye_ingles.
        /// </summary>
        internal static string noIncluyeGet {
            get {
                return ResourceManager.GetString("noIncluyeGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombreIngles.
        /// </summary>
        internal static string nombreGET {
            get {
                return ResourceManager.GetString("nombreGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombreIngles.
        /// </summary>
        internal static string nombrePGET {
            get {
                return ResourceManager.GetString("nombrePGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our Email.
        /// </summary>
        internal static string nuestroEmail {
            get {
                return ResourceManager.GetString("nuestroEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        internal static string Observa {
            get {
                return ResourceManager.GetString("Observa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        internal static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a observacionesIngles.
        /// </summary>
        internal static string observacionesGet {
            get {
                return ResourceManager.GetString("observacionesGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Packages.
        /// </summary>
        internal static string paquetes {
            get {
                return ResourceManager.GetString("paquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to quote an exclusive package?.
        /// </summary>
        internal static string PaqueteViP {
            get {
                return ResourceManager.GetString("PaqueteViP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Person.
        /// </summary>
        internal static string persona {
            get {
                return ResourceManager.GetString("persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ask.
        /// </summary>
        internal static string preguntar {
            get {
                return ResourceManager.GetString("preguntar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can contact us from 09:00 a.m to 08:00 p.m. to.
        /// </summary>
        internal static string puedeContactarnos {
            get {
                return ResourceManager.GetString("puedeContactarnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recommendations.
        /// </summary>
        internal static string recomendaciones {
            get {
                return ResourceManager.GetString("recomendaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recomendaciones_ingles.
        /// </summary>
        internal static string recomendacionesGet {
            get {
                return ResourceManager.GetString("recomendacionesGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tours.
        /// </summary>
        internal static string tours {
            get {
                return ResourceManager.GetString("tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
    }
}
