//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.LoginResourceUS", typeof(LoginResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Here.
        /// </summary>
        internal static string aqui {
            get {
                return ResourceManager.GetString("aqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blog.
        /// </summary>
        internal static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string contraseña {
            get {
                return ResourceManager.GetString("contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dar Click.
        /// </summary>
        internal static string dar {
            get {
                return ResourceManager.GetString("dar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string iniciarsesion {
            get {
                return ResourceManager.GetString("iniciarsesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a introduccionIngles.
        /// </summary>
        internal static string introduccion {
            get {
                return ResourceManager.GetString("introduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Email and Password.
        /// </summary>
        internal static string introducir {
            get {
                return ResourceManager.GetString("introducir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ MORE.
        /// </summary>
        internal static string leerMas {
            get {
                return ResourceManager.GetString("leerMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombreIngles.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Did you forget your password?.
        /// </summary>
        internal static string olvidaste {
            get {
                return ResourceManager.GetString("olvidaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To reset your password.
        /// </summary>
        internal static string pararesetear {
            get {
                return ResourceManager.GetString("pararesetear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Popular Posts.
        /// </summary>
        internal static string publicacionespulares {
            get {
                return ResourceManager.GetString("publicacionespulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        internal static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tituloIngles.
        /// </summary>
        internal static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
    }
}
