//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiCuentaResourceMX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiCuentaResourceMX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.MiCuentaResourceMX", typeof(MiCuentaResourceMX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string cambiarcontraseña {
            get {
                return ResourceManager.GetString("cambiarcontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        internal static string colonia {
            get {
                return ResourceManager.GetString("colonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        internal static string confirmarcontraseña {
            get {
                return ResourceManager.GetString("confirmarcontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Actual.
        /// </summary>
        internal static string contraseñaactual {
            get {
                return ResourceManager.GetString("contraseñaactual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string correoelectronico {
            get {
                return ResourceManager.GetString("correoelectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizaciones.
        /// </summary>
        internal static string cotizaciones {
            get {
                return ResourceManager.GetString("cotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        internal static string detalles {
            get {
                return ResourceManager.GetString("detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil.
        /// </summary>
        internal static string editarperfil {
            get {
                return ResourceManager.GetString("editarperfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha LLegada.
        /// </summary>
        internal static string fecha_llegada {
            get {
                return ResourceManager.GetString("fecha_llegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Nacimiento.
        /// </summary>
        internal static string fecha_nacimiento {
            get {
                return ResourceManager.GetString("fecha_nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Salida.
        /// </summary>
        internal static string fecha_salida {
            get {
                return ResourceManager.GetString("fecha_salida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Solicitud.
        /// </summary>
        internal static string fecha_solicitud {
            get {
                return ResourceManager.GetString("fecha_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero.
        /// </summary>
        internal static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        internal static string guardarcambios {
            get {
                return ResourceManager.GetString("guardarcambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Personal.
        /// </summary>
        internal static string informacionpersonal {
            get {
                return ResourceManager.GetString("informacionpersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        internal static string micuenta {
            get {
                return ResourceManager.GetString("micuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string municipio {
            get {
                return ResourceManager.GetString("municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string nuevascontraseña {
            get {
                return ResourceManager.GetString("nuevascontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        internal static string solicitud {
            get {
                return ResourceManager.GetString("solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Solicitud.
        /// </summary>
        internal static string tipo_solicitud {
            get {
                return ResourceManager.GetString("tipo_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tours.
        /// </summary>
        internal static string tour {
            get {
                return ResourceManager.GetString("tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportación.
        /// </summary>
        internal static string transportacion {
            get {
                return ResourceManager.GetString("transportacion", resourceCulture);
            }
        }
    }
}
