//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.ResourceMX", typeof(ResourceMX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención al cliente.
        /// </summary>
        internal static string atencion {
            get {
                return ResourceManager.GetString("atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blog.
        /// </summary>
        internal static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string changeLocale {
            get {
                return ResourceManager.GetString("changeLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conocenos.
        /// </summary>
        internal static string conocenos {
            get {
                return ResourceManager.GetString("conocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta nuestros.
        /// </summary>
        internal static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinos.
        /// </summary>
        internal static string destino {
            get {
                return ResourceManager.GetString("destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige.
        /// </summary>
        internal static string elige {
            get {
                return ResourceManager.GetString("elige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galería.
        /// </summary>
        internal static string galeria {
            get {
                return ResourceManager.GetString("galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoteles.
        /// </summary>
        internal static string hoteles {
            get {
                return ResourceManager.GetString("hoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string ingresar {
            get {
                return ResourceManager.GetString("ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string inicio {
            get {
                return ResourceManager.GetString("inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en.
        /// </summary>
        internal static string locale {
            get {
                return ResourceManager.GetString("locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paquetes.
        /// </summary>
        internal static string paquetes {
            get {
                return ResourceManager.GetString("paquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promociones.
        /// </summary>
        internal static string promocion {
            get {
                return ResourceManager.GetString("promocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendaciones.
        /// </summary>
        internal static string recomendaciones {
            get {
                return ResourceManager.GetString("recomendaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar a inicio.
        /// </summary>
        internal static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a términos y condiciones.
        /// </summary>
        internal static string terminoYcondiciones {
            get {
                return ResourceManager.GetString("terminoYcondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tours.
        /// </summary>
        internal static string tours {
            get {
                return ResourceManager.GetString("tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tours .
        /// </summary>
        internal static string tours_empresa {
            get {
                return ResourceManager.GetString("tours_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportación.
        /// </summary>
        internal static string transportacion {
            get {
                return ResourceManager.GetString("transportacion", resourceCulture);
            }
        }
    }
}
