//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeccionResourceMX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeccionResourceMX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.SeccionResourceMX", typeof(SeccionResourceMX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clima.
        /// </summary>
        internal static string clima {
            get {
                return ResourceManager.GetString("clima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizar.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcion.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcion.
        /// </summary>
        internal static string descripcionGET {
            get {
                return ResourceManager.GetString("descripcionGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcion.
        /// </summary>
        internal static string descripcionTag {
            get {
                return ResourceManager.GetString("descripcionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string desde {
            get {
                return ResourceManager.GetString("desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DÍAS.
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Cotización.
        /// </summary>
        internal static string finalizarCotizar {
            get {
                return ResourceManager.GetString("finalizarCotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formas de Pago.
        /// </summary>
        internal static string formasPago {
            get {
                return ResourceManager.GetString("formasPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a frase.
        /// </summary>
        internal static string frase {
            get {
                return ResourceManager.GetString("frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a newsletter.
        /// </summary>
        internal static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOCHES.
        /// </summary>
        internal static string noches {
            get {
                return ResourceManager.GetString("noches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string nombreGET {
            get {
                return ResourceManager.GetString("nombreGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string nombreTag {
            get {
                return ResourceManager.GetString("nombreTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero 1.
        /// </summary>
        internal static string numeroUno {
            get {
                return ResourceManager.GetString("numeroUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formas de pago.
        /// </summary>
        internal static string pago {
            get {
                return ResourceManager.GetString("pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pieAcerca.
        /// </summary>
        internal static string pieAcerca {
            get {
                return ResourceManager.GetString("pieAcerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paquetes Populares.
        /// </summary>
        internal static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntar.
        /// </summary>
        internal static string preguntar {
            get {
                return ResourceManager.GetString("preguntar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promociones.
        /// </summary>
        internal static string promociones {
            get {
                return ResourceManager.GetString("promociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendaciones.
        /// </summary>
        internal static string recomendaciones {
            get {
                return ResourceManager.GetString("recomendaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestros servicios.
        /// </summary>
        internal static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguenos.
        /// </summary>
        internal static string siguenos {
            get {
                return ResourceManager.GetString("siguenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscribirse.
        /// </summary>
        internal static string suscribirse {
            get {
                return ResourceManager.GetString("suscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a textoDos.
        /// </summary>
        internal static string textoDos {
            get {
                return ResourceManager.GetString("textoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a textoUno.
        /// </summary>
        internal static string textoUno {
            get {
                return ResourceManager.GetString("textoUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a titulo.
        /// </summary>
        internal static string tituloArticulo {
            get {
                return ResourceManager.GetString("tituloArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a topCinco.
        /// </summary>
        internal static string topCinco {
            get {
                return ResourceManager.GetString("topCinco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima Publicación.
        /// </summary>
        internal static string ultimaPublicacion {
            get {
                return ResourceManager.GetString("ultimaPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver más.
        /// </summary>
        internal static string verMas {
            get {
                return ResourceManager.GetString("verMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
    }
}
