//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToursResourceMX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToursResourceMX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.ToursResourceMX", typeof(ToursResourceMX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Armar Paquete VIP.
        /// </summary>
        internal static string armarPaquete {
            get {
                return ResourceManager.GetString("armarPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contamos con mas de.
        /// </summary>
        internal static string contamosConMas {
            get {
                return ResourceManager.GetString("contamosConMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcion.
        /// </summary>
        internal static string descripcionGET {
            get {
                return ResourceManager.GetString("descripcionGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIAS.
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string filtrar {
            get {
                return ResourceManager.GetString("filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupal.
        /// </summary>
        internal static string grupal {
            get {
                return ResourceManager.GetString("grupal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modalidad.
        /// </summary>
        internal static string Modalidad {
            get {
                return ResourceManager.GetString("Modalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué modalidad prefieres?.
        /// </summary>
        internal static string modaliPrefi {
            get {
                return ResourceManager.GetString("modaliPrefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOCHES.
        /// </summary>
        internal static string noches {
            get {
                return ResourceManager.GetString("noches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string nombreGET {
            get {
                return ResourceManager.GetString("nombreGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string nombreTag {
            get {
                return ResourceManager.GetString("nombreTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LE OFRECEMOS EL SERVICIO DE PAQUETES VIP, DONDE USTED USTED DECIDE QUE VISITAR Y TODAS LAS CARACTERÍSTICAS DE SU VIAJE PARA QUE SU EXPERIENCIA SEA ÚNICA E INOLVIDABLE.
        /// </summary>
        internal static string paqueteVIPText {
            get {
                return ResourceManager.GetString("paqueteVIPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privado.
        /// </summary>
        internal static string privado {
            get {
                return ResourceManager.GetString("privado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Que viaje prefieres.
        /// </summary>
        internal static string queViaje {
            get {
                return ResourceManager.GetString("queViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas diarias.
        /// </summary>
        internal static string Salidas {
            get {
                return ResourceManager.GetString("Salidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string todos {
            get {
                return ResourceManager.GetString("todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tours Diarios.
        /// </summary>
        internal static string tour {
            get {
                return ResourceManager.GetString("tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tours.
        /// </summary>
        internal static string tours {
            get {
                return ResourceManager.GetString("tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
    }
}
