//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativaSl.Web.ViajesPorChiapas.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransportacionResourceUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportacionResourceUS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreativaSl.Web.ViajesPorChiapas.Resources.TransportacionResourceUS", typeof(TransportacionResourceUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mother&apos;s Last Name.
        /// </summary>
        internal static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you need help feel free to contact us and we will support it.
        /// </summary>
        internal static string ayuda {
            get {
                return ResourceManager.GetString("ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact Agent.
        /// </summary>
        internal static string contactarAgente {
            get {
                return ResourceManager.GetString("contactarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have all the experience in executive transportation.
        /// </summary>
        internal static string contamosExperienciaTrasnportacionEjecutiva {
            get {
                return ResourceManager.GetString("contamosExperienciaTrasnportacionEjecutiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quote.
        /// </summary>
        internal static string cotizar {
            get {
                return ResourceManager.GetString("cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportation Quote.
        /// </summary>
        internal static string cotizarTransportacion {
            get {
                return ResourceManager.GetString("cotizarTransportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service Description.
        /// </summary>
        internal static string descripcionServicio {
            get {
                return ResourceManager.GetString("descripcionServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcionTransportacionIngles.
        /// </summary>
        internal static string descripcionTransportacion {
            get {
                return ResourceManager.GetString("descripcionTransportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        internal static string detalles {
            get {
                return ResourceManager.GetString("detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service Detail.
        /// </summary>
        internal static string detalleServicio {
            get {
                return ResourceManager.GetString("detalleServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a detalleTransportacionIngles.
        /// </summary>
        internal static string detalleTransportacion {
            get {
                return ResourceManager.GetString("detalleTransportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Mail.
        /// </summary>
        internal static string enviarCorreo {
            get {
                return ResourceManager.GetString("enviarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrival date.
        /// </summary>
        internal static string fechaLlegada {
            get {
                return ResourceManager.GetString("fechaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure Date.
        /// </summary>
        internal static string fechaSalida {
            get {
                return ResourceManager.GetString("fechaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In.
        /// </summary>
        internal static string horaLlegada {
            get {
                return ResourceManager.GetString("horaLlegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departure Time.
        /// </summary>
        internal static string horaSalida {
            get {
                return ResourceManager.GetString("horaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor 0-2.
        /// </summary>
        internal static string menores14 {
            get {
                return ResourceManager.GetString("menores14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor 3-10.
        /// </summary>
        internal static string menores511 {
            get {
                return ResourceManager.GetString("menores511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quote Data.
        /// </summary>
        internal static string nombrePaquete {
            get {
                return ResourceManager.GetString("nombrePaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Adults.
        /// </summary>
        internal static string numeroAdultos {
            get {
                return ResourceManager.GetString("numeroAdultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of People.
        /// </summary>
        internal static string numeroPersonas {
            get {
                return ResourceManager.GetString("numeroPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVE.
        /// </summary>
        internal static string reserv {
            get {
                return ResourceManager.GetString("reserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserve.
        /// </summary>
        internal static string reservar {
            get {
                return ResourceManager.GetString("reservar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In a period of 24 hours one of our agents will notify you by email if there is availability of the services.
        /// </summary>
        internal static string termin24Horas {
            get {
                return ResourceManager.GetString("termin24Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of car.
        /// </summary>
        internal static string tipoCarro {
            get {
                return ResourceManager.GetString("tipoCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please specify the range of people traveling.
        /// </summary>
        internal static string validacionLoad1 {
            get {
                return ResourceManager.GetString("validacionLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please indicate the number of people per room , remember that only a maximum of 4 persons per room is allowed.
        /// </summary>
        internal static string validacionLoad2 {
            get {
                return ResourceManager.GetString("validacionLoad2", resourceCulture);
            }
        }
    }
}
